version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
  release:
    docker:
      - image: circleci/node:12
    steps:
      - run: |
          mkdir -p /home/circleci/project
          cd /home/circleci/project
          git clone "https://$GH_TOKEN@github.com/herteleo/vue-mu.git" .
          git config user.email "leonard.hertel@gmail.com"
          git config user.name "herteleo"
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm ci
      - run: npm run release

workflows:
  version: 2
  lint_and_release:
    jobs:
      - lint
      - release:
          requires:
            - lint
          filters:
            branches:
              only:
                - master
